services:
  php:
    image: php-fpm
    build: .
    volumes:
      - ./test:/var/www/html/public
      - ./test/test.sh:/tmp/test.sh
    environment:
      - APP_ENV=${APP_ENV}
    # command: bash /tmp/test.sh
