version: '3.2'
services:
  php:
    build: .
    volumes:
      - ./test/index.php:/var/www/html/public/index.php
      - php_unix_socket:/run/php/
    environment:
      - APP_ENV=${APP_ENV}
  sut:
    image: opositatest/nginx:v2.0
    volumes:
      - ./test/index.php:/var/www/html/public/index.php
      - ./test/test.sh:/tmp/test.sh
      - php_unix_socket:/run/php/
    environment:
      - APP_ENV=${APP_ENV}
    depends_on:
      - php
    command: bash /tmp/test.sh

volumes:
  php_unix_socket: