version: 3.7
jobs:
  build:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run: docker-compose -f docker-compose.test.yml build

      # run test
      - run: docker-compose -f docker-compose.test.yml up --abort-on-container-exit