name: CICD
on:
  push:
    tags: [ "*" ]
    branches: [ "main" ]
  workflow_dispatch:
env:
  DOCKERHUB_REPOSITORY: opositatest/php-fpm

jobs:
  test:
    uses: ./.github/workflows/test.yml
    secrets: inherit

  cicd:
    runs-on: ${{ matrix.runner }}
    timeout-minutes: 20
    strategy:
      matrix:
        include:
          - runner: public-ubuntu-latest-arm64
          - runner: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Get the version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

    - name: Check if latest
      id: latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: echo ::set-output name=latest::true

    - name: Build, tag and push image to Dockerhub
      env:
        LATEST: ${{ steps.latest.outputs.latest }}
        VERSION: ${{ steps.get_version.outputs.version }}
      run: |
        [[ ${LATEST} == "true" ]] && version="latest" || version=${VERSION}
        docker build -t ${DOCKERHUB_REPOSITORY}:${version} .
        docker push ${DOCKERHUB_REPOSITORY}:${version}