name: CICD
on:
  push:
    tags: [ "*" ]
    branches: [ "main" ]
  workflow_dispatch:
env:
  DOCKERHUB_REPOSITORY: opositatest/php-fpm

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  build:
    # needs: test
    name: build
    runs-on: ubuntu-24.04-arm64
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get the version
        id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Check if latest
        id: latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "version=latest" >> $GITHUB_ENV

      - name: Build, tag and push image to Docker Hub and ECR arm64
        id: build-arm64
        run: |
          docker build \
            --platform linux/arm64 \
            -t ${DOCKERHUB_REPOSITORY}:${version} .
          docker push ${DOCKERHUB_REPOSITORY}:${version}
      
      - name: Build, tag and push image to Docker Hub and ECR amd64
        id: build-amd64
        run: |
          docker build \
            --platform linux/arm64,linux/amd64 \
            -t ${DOCKERHUB_REPOSITORY}:${version} .
          docker push ${DOCKERHUB_REPOSITORY}:${version}
