name: CICD
on:
  push:
    tags: [ "*" ]
    branches: [ "main" ]
  workflow_dispatch:
env:
  DOCKERHUB_REPOSITORY: opositatest/php-fpm

jobs:
  # test:
  #   uses: ./.github/workflows/test.yml
  #   secrets: inherit

  build:
    # needs: test
    name: build
    runs-on: public-ubuntu-latest-arm64
    timeout-minutes: 20

    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Get the version
        id: get_version
        run: echo "version=${GITHUB_REF/refs\/tags\//}" >> $GITHUB_ENV

      - name: Check if latest
        id: latest
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: echo "version=latest" >> $GITHUB_ENV

      - name: Install drivers
        run: |
          docker buildx create --use --name multiarch-builder
          docker buildx inspect --bootstrap

      - name: Build and tag image to Docker Hub and ECR arm64
        id: build-arm64
        run: |
          docker buildx build --platform linux/arm64 \
          -t ${DOCKERHUB_REPOSITORY}:${version}-arm64 \
          --load .
      
      - name: Build and tag image to Docker Hub and ECR amd64
        id: build-amd64
        run: |
          docker buildx build --platform linux/amd64 \
            -t ${DOCKERHUB_REPOSITORY}:${version}-amd64 \
            --load .

      - name: Create and push multi-arch manifest
        id: push-multiarch
        run: |
          docker buildx imagetools create \
            --tag ${DOCKERHUB_REPOSITORY}:${version} \
            ${DOCKERHUB_REPOSITORY}:${version}-amd64 \
            ${DOCKERHUB_REPOSITORY}:${version}-arm64            