name: CICD
on:
  push:
    tags: [ '*' ]
    branches: [ "main" ]
  workflow_dispatch:
env:
  DOCKERHUB_REPOSITORY: opositatest/php-fpm

jobs:
  cicd:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
    - uses: actions/checkout@v4
    - uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}

    - name: Build
      run: docker compose -f docker-compose.test.yml build
    - name: Run test
      run: docker compose -f docker-compose.test.yml up --abort-on-container-exit

    - name: Get the version
      id: get_version
      run: echo ::set-output name=version::${GITHUB_REF/refs\/tags\//}

    - name: Check if latest
      id: latest
      if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      run: echo ::set-output name=latest::true

    - name: Build, tag and push image to Dockerhub
      env:
        LATEST: ${{ steps.latest.outputs.latest }}
        VERSION: ${{ steps.get_version.outputs.version }}
      run: |
        [[ ${LATEST} == "true" ]] && version="latest" || version=${VERSION}
        docker buildx build \
          --platform linux/arm64,linux/amd64 \
          --tag ${DOCKERHUB_REPOSITORY}:${version} \
          -- push .